[package]
name = "pepmatch_rs_engine"
version = "1.16.0"
edition = "2024"

[lib]
name = "_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24", features = ["extension-module"] }
memmap2 = "0.9"
rayon = "1.10"

[profile.release]
opt-level = 3
lto = true
